name: Go CI Pipeline for Multiple Projects

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: HelloWorld  # Katalog HelloWorld

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Go 1.22.5 manually
        run: |
          wget https://golang.org/dl/go1.22.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xvzf go1.22.5.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          go version  # Sprawdzenie wersji Go

      - name: Check HelloWorld directory
        run: |
          ls -alh  # Wyświetlamy zawartość katalogu roboczego HelloWorld

      - name: Install dependencies for HelloWorld
        run: |
          go mod tidy  # Instalujemy zależności

      - name: Run tests for HelloWorld
        run: go test ./...

  your-name:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: YourName  # Katalog YourName

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Go 1.22.5 manually
        run: |
          wget https://golang.org/dl/go1.22.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xvzf go1.22.5.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          go version  # Sprawdzenie wersji Go

      - name: Check YourName directory
        run: |
          ls -alh  # Wyświetlamy zawartość katalogu roboczego YourName

      - name: Install dependencies for YourName
        run: |
          go mod tidy  # Instalujemy zależności

      - name: Run tests for YourName
        run: go test ./...
