name: Go CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.5

      - name: Change to HelloWorld directory
        run: cd HelloWorld && go mod tidy

      - name: Run tests
        run: cd HelloWorld && go test ./...
